name: yt_attic
dependencies:
- openssl=1.0.2k=2
- pip=9.0.1=py35_1
- python=3.5.3=1
- readline=6.2=2
- setuptools=27.2.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - appnope==0.1.0
  - cycler==0.10.0
  - cython==0.25.2
  - decorator==4.0.11
  - h5py==2.7.0
  - ipython==6.0.0
  - ipython-genutils==0.2.0
  - jedi==0.10.2
  - matplotlib==2.0.2
  - mpmath==0.19
  - numpy==1.12.1
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - prompt-toolkit==1.0.14
  - ptyprocess==0.5.1
  - pygments==2.2.0
  - pyparsing==2.2.0
  - python-dateutil==2.6.0
  - pytz==2017.2
  - simplegeneric==0.8.1
  - six==1.10.0
  - sphinx-bootstrap-theme==0.4.14
  - sympy==1.0
  - traitlets==4.3.2
  - wcwidth==0.1.7
  - yt==3.3.5
